name: sense-i
favicon: null
layout_spectrum: 0.9064547
typography_spectrum: 0.3297491
title: Haptic and tactile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-11348977-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F5491'
    - '#1E1F17'
    - '#EACFA3'
    - '#CFEBFC'
    - '#88885C'
  brandStrength: 1
  lightness: 0.5285478
  saturation: 0.1801417
  rhythmicContrast: 0.4591548
purpose: []
