name: sense-i
favicon: null
layout_spectrum: 0.99932
typography_spectrum: 0.3297491
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: A curation of alternative sensory inputs in human-machine interaction
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecebe6'
    - '#c2b2a3'
    - '#e68340'
    - '#3b190d'
    - '#dc5306'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
